const SHEET_ID='1FcetqNVvXNI78h0mcQdEJBEVXzkHcgaddFrCn2VOugk';
const SHEET_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=${encodeURIComponent('Активности')}&headers=0&range=A2:D`;
const EVENTS_SHEET_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=${encodeURIComponent('Ивенты')}&headers=0&range=A2:I`;
const BOOKING_API_URL='https://script.google.com/macros/s/AKfycbwpYRqIunVa1uBfMqaf9HY4ICKXeeaCUbYLtoBxYT6e0_tYyBSvgiVfmeU-3SkEC2SqxQ/exec';
const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();tg.setBackgroundColor?.('bg_color');}
const user=tg?.initDataUnsafe?.user,hello=document.getElementById('hello');if(user)hello.textContent=`Здравствуйте, ${user.first_name||'гость'}!`;
const activitiesContainer=document.getElementById('activities'),calendar=document.getElementById('calendar'),message=document.getElementById('message'),activityModal=document.getElementById('activity-modal'),activityTitle=document.getElementById('activity-title'),activityDescription=document.getElementById('activity-description'),activityImageWrap=document.getElementById('activity-image-wrap'),activityImage=document.getElementById('activity-image'),modalClose=document.getElementById('modal-close'),modalOk=document.getElementById('modal-ok'),eventsModal=document.getElementById('events-modal'),eventsTitle=document.getElementById('events-title'),eventsList=document.getElementById('events-list'),eventsClose=document.getElementById('events-close');
const fallbackActivities=[{key:'diogen',title:'Диоген',description:'Можно прийти в мастерскую и провести время в своём ритме: поработать над чем-то своим, потискать кожу, попить чаю, посидеть в тишине или вообще ничего не делать.',image:''},{key:'masterclass',title:'Мастер-класс',description:'Вы выбираете изделие и приходите делать его вместе с мастером. Мастер-класс проходит в заданное время и длится столько, сколько указано в его описании.',image:''},{key:'order',title:'Обсудить заказ',description:'Если вы хотите сделать изделие на заказ, можно прийти в мастерскую лично: обсудить задумку, материалы, размеры, детали и все нюансы будущей вещи.',image:''}];
let activities=fallbackActivities,events=[],bookingSlots=[],selectedCalendar={format:'',name:''};
const CALENDAR_START_HOUR=10,CALENDAR_END_HOUR=20,CALENDAR_DAYS=30;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');
function parse(t){const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<=a)throw Error('Google Таблица не вернула данные.');return JSON.parse(t.slice(a,b+1));}function cell(c,i,f=''){return c[i]?.v??f;}function norm(v){return String(v||'').trim().toLowerCase();}
function dateKey(s){const [d,m,y]=String(s).split(' ')[0].split('.').map(Number);return new Date(y,m-1,d,12,0,0);}function dateText(d){return d.toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'}).replace(' г.','');}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x;}function pad(n){return String(n).padStart(2,'0');}function dateString(d){return`${pad(d.getDate())}.${pad(d.getMonth()+1)}.${d.getFullYear()}`;}
async function loadActivities(){activitiesContainer.innerHTML='<div class="loading">Загрузка активностей...</div>';try{const r=await fetch(SHEET_URL,{cache:'no-store'});const j=parse(await r.text());activities=j.table.rows.map((x,i)=>{const c=x.c||[];return{key:String(cell(c,0,`activity-${i}`)).trim().toLowerCase(),title:String(cell(c,1,'Без названия')).trim(),description:String(cell(c,2,'')).trim(),image:String(cell(c,3,'')).trim()};}).filter(x=>x.key&&x.title);renderActivities();}catch(e){activitiesContainer.innerHTML=`<div class="load-error">Не удалось загрузить активности: ${esc(e.message)}</div>`;}}
async function loadEvents(){try{const r=await fetch(EVENTS_SHEET_URL,{cache:'no-store'});const j=parse(await r.text());const rows=j.table.rows||[];events=rows.map((x,i)=>{const c=x.c||[];return{activity:String(cell(c,0,'')).trim(),name:String(cell(c,1,'Без названия')).trim(),price:String(cell(c,2,'')).trim(),age:String(cell(c,3,'')).trim(),duration:String(cell(c,4,'')).trim(),complexity:String(cell(c,5,'')).trim(),image:String(cell(c,6,'')).trim(),description:String(cell(c,8,'')).trim(),index:i};}).filter(x=>x.activity&&x.name);}catch(e){console.error(e);events=[];}}
async function loadBookingData(){try{const r=await fetch(BOOKING_API_URL,{cache:'no-store'});const j=await r.json();if(!j.ok)throw Error(j.error||'Не удалось получить календарь.');bookingSlots=Array.isArray(j.slots)?j.slots:[];renderCalendar();return j;}catch(e){bookingSlots=[];renderCalendar();throw e;}}
async function apiBook(slot,tickets,endTime=''){if(!user?.id)throw Error('Не удалось определить Telegram ID. Откройте запись внутри Telegram.');const payload={action:'book',telegramId:String(user.id),name:String(user.first_name||user.username||'гость'),format:slot.format,eventName:slot.name,date:slot.start.split(' ')[0],time:slot.start.split(' ')[1],tickets:Number(tickets),endTime};const r=await fetch(BOOKING_API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const j=await r.json();if(!j.ok)throw Error(j.error||'Не удалось создать бронь.');return j;}
function renderActivities(){activitiesContainer.innerHTML=activities.map(a=>`<button class="choice" type="button" data-action="${esc(a.key)}"><span class="choice-icon">${a.key==='diogen'?'◌':a.key==='masterclass'?'✦':'✎'}</span><span><strong>${esc(a.title)}</strong><small>${esc(a.description)}</small></span><span class="choice-calendar"><span class="choice-calendar-icon">▣</span><span class="choice-calendar-arrow">↓</span></span></button>`).join('');activitiesContainer.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',e=>e.target.closest('.choice-calendar')?openEventChooser(b.dataset.action):openActivity(b.dataset.action)));}
function openActivity(k){const a=activities.find(x=>x.key===k);if(!a)return;activityTitle.textContent=a.title;activityDescription.textContent=a.description;if(a.image){activityImage.src=a.image;activityImage.alt=a.title;activityImageWrap.classList.remove('hidden');}else activityImageWrap.classList.add('hidden');activityModal.classList.remove('hidden');}
function stars(v){const n=Math.max(0,Math.min(5,parseInt(v,10)||0));return[1,2,3,4,5].map(i=>`<span class="complexity-star${i>5-n?' filled':''}">★</span>`).join('');}
function openEventChooser(k){const key=norm(k);if(key==='order'){closeEvents();selectedCalendar={format:'',name:''};renderCalendar();showMessage('Для обсуждения заказа свяжитесь с мастерской.');return;}const a=activities.find(x=>norm(x.key)===key);if(!a)return;const list=events.filter(x=>norm(x.activity)===key);eventsTitle.textContent=a.title;eventsList.innerHTML=list.length?list.map((e,i)=>`<article class="event-card"><div class="event-image-wrap ${e.image?'':'empty'}">${e.image?`<img class="event-image" src="${esc(e.image)}" alt="${esc(e.name)}">`:'Фото пока нет'}<div class="event-overlay"><div class="event-text-block"><h3>${esc(e.name)}</h3><strong class="event-price">${esc(e.price||'—')} р</strong></div><div class="event-age"><strong>${esc(e.age||'—')}</strong></div><div class="event-duration"><strong>${esc(e.duration||'—')}</strong></div><div class="event-complexity"><strong class="complexity-stars">${stars(e.complexity)}</strong></div></div><div class="event-actions"><button class="event-details" type="button" data-i="${i}">Подробнее</button><button class="event-book" type="button" data-i="${i}">Записаться</button></div></div><div class="event-description hidden" data-i="${i}">${esc(e.description||'Описание пока придумываем')}</div></article>`).join(''):'<div class="events-empty">Пока нет доступных вариантов.</div>';eventsList.querySelectorAll('.event-details').forEach(b=>b.addEventListener('click',()=>{const d=eventsList.querySelector(`.event-description[data-i="${b.dataset.i}"]`);if(!d)return;const open=!d.classList.contains('hidden');d.classList.toggle('hidden');b.textContent=open?'Подробнее':'Свернуть';}));eventsList.querySelectorAll('.event-book').forEach(b=>b.addEventListener('click',()=>{const e=list[+b.dataset.i];closeEvents();goToCalendar(key,e.name);}));eventsModal.classList.remove('hidden');}
function closeEvents(){eventsModal.classList.add('hidden');}
function selectedSlots(){return bookingSlots;}
function slotClass(s){if(!s.available)return'closed';if(s.occupied>0)return s.format==='МК'?'mk':'dio';return'free';}
function slotTime(s){return s.start.split(' ')[1];}
function slotMinutes(s){const [h,m]=slotTime(s).split(':').map(Number);return h*60+m;}
function slotEndMinutes(s){const [h,m]=s.end.split(' ')[1].split(':').map(Number);return h*60+m;}
function slotLabel(s){if(!s.available)return'мест нет';if(s.occupied>0)return`${s.occupied}/${s.capacity}`;return`свободно ${s.capacity}/${s.capacity}`;}
function weekStart(){const today=new Date();today.setHours(12,0,0,0);return today;}
function calendarHourHeight(){const h=Math.max(1,calendar.getBoundingClientRect().height-48);return h/10;}
function durationHours(event){const match=String(event?.duration||'').match(/\d+(?:[.,]\d+)?/);return match?Math.max(1,Number(match[0].replace(',','.'))):1;}
function availableDiogenEnd(slot,tickets=1){const start=slotMinutes(slot),day=slot.start.split(' ')[0],hours=[];for(let h=start/60+1;h<=CALENDAR_END_HOUR;h++){const next=bookingSlots.find(s=>s.format==='Диоген'&&s.start.startsWith(day)&&slotMinutes(s)===(h-1)*60);if(!next||!next.available||Number(next.free||0)<tickets)break;hours.push(h*60);}return hours;}
function candidateSlotsForEvent(eventName){const event=events.find(e=>norm(e.name)===norm(eventName)&&norm(e.activity)==='masterclass');if(!event)return[];const needed=durationHours(event);return bookingSlots.filter(s=>s.format==='МК'&&norm(s.name)===norm(eventName)&&s.available&&Number(s.free||0)>0).filter(s=>{const start=slotMinutes(s),end=slotEndMinutes(s),day=s.start.split(' ')[0];if((end-start)/60>=needed)return true;for(let i=0;i<needed;i++){const part=bookingSlots.find(x=>x.format==='МК'&&x.start.startsWith(day)&&slotMinutes(x)===start+i*60&&norm(x.name)===norm(eventName));if(!part||!part.available||Number(part.free||0)<=0)return false;}return true;});}
function renderCalendar(){const first=weekStart(),days=Array.from({length:CALENDAR_DAYS},(_,i)=>addDays(first,i)),slots=selectedSlots(),hourHeight=calendarHourHeight();calendar.innerHTML=`<div class="calendar-scroll"><div class="calendar-grid"><div class="calendar-corner"></div><div class="calendar-days">${days.map(d=>`<div class="calendar-day-head">${esc(dateText(d))}</div>`).join('')}</div><div class="calendar-times">${Array.from({length:CALENDAR_END_HOUR-CALENDAR_START_HOUR},(_,i)=>`<div class="calendar-time">${pad(CALENDAR_START_HOUR+i)}:00</div>`).join('')}<div class="calendar-time-end">20:00</div></div><div class="calendar-columns">${days.map(d=>{const ds=dateString(d);const daySlots=slots.filter(s=>s.start.startsWith(ds));return`<div class="calendar-column"><div class="calendar-hour-lines">${Array.from({length:CALENDAR_END_HOUR-CALENDAR_START_HOUR},()=>'<div></div>').join('')}</div>${daySlots.map(s=>{const start=Math.max(slotMinutes(s),CALENDAR_START_HOUR*60),end=Math.min(slotEndMinutes(s),CALENDAR_END_HOUR*60);if(end<=start)return'';const top=(start-CALENDAR_START_HOUR*60)/60*hourHeight,height=(end-start)/60*hourHeight-3;const state=slotClass(s);const candidate=selectedCalendar.format==='МК'&&candidateSlotsForEvent(selectedCalendar.name).some(x=>x.slotId===s.slotId)||selectedCalendar.format==='Диоген'&&s.format!=='МК'&&s.available&&Number(s.free||0)>0;return`<button class="calendar-slot ${state}${candidate?' candidate':''}" type="button" data-slot-id="${esc(s.slotId)}" style="top:${top}px;height:${height}px"><strong>${esc(slotTime(s))}–${esc(s.end.split(' ')[1])}</strong><small>${esc(s.format==='МК'?`МК — ${s.name}`:`Диоген — ${s.name}`)} · ${esc(slotLabel(s))}</small></button>`;}).join('')}</div>`;}).join('')}</div></div></div>`;calendar.querySelectorAll('.calendar-slot').forEach(b=>b.addEventListener('click',()=>{const s=bookingSlots.find(x=>x.slotId===b.dataset.slotId);if(s)selectSlot(s);}));}
function ensureBookingModal(){if(document.getElementById('booking-modal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="booking-modal" class="modal hidden" role="dialog" aria-modal="true" aria-labelledby="booking-title"><div class="modal-content booking-modal-content"><button id="booking-close" class="modal-close" type="button" aria-label="Закрыть">×</button><p class="eyebrow">ЗАПИСЬ</p><h2 id="booking-title">Записаться</h2><div id="booking-activity" class="booking-activity"></div><div class="booking-date-row"><div class="booking-time-wrap"><button id="booking-start" class="booking-time" type="button"></button><span class="booking-dash">–</span><button id="booking-end" class="booking-time" type="button"></button></div><div id="booking-date" class="booking-date"></div></div><div id="booking-duration-controls" class="booking-duration-controls hidden"><button id="booking-end-up" class="booking-arrow" type="button" aria-label="Увеличить длительность">↑</button><button id="booking-end-down" class="booking-arrow" type="button" aria-label="Уменьшить длительность">↓</button></div><div class="booking-tickets"><label for="booking-tickets-input">Количество мест</label><input id="booking-tickets-input" type="number" min="1" value="1"></div><button id="booking-submit" class="modal-ok" type="button">Записаться</button></div></div>`);const modal=document.getElementById('booking-modal');document.getElementById('booking-close').addEventListener('click',closeBooking);modal.addEventListener('click',e=>{if(e.target===modal)closeBooking();});document.getElementById('booking-submit').addEventListener('click',submitBooking);document.getElementById('booking-tickets-input').addEventListener('input',renderBookingModal);document.getElementById('booking-end-up').addEventListener('click',()=>changeDiogenEnd(1));document.getElementById('booking-end-down').addEventListener('click',()=>changeDiogenEnd(-1));}
let bookingState=null;
function openBooking(slot){ensureBookingModal();bookingState={slot,start:slotMinutes(slot),end:slotEndMinutes(slot),tickets:1};const title=selectedCalendar.name||slot.name||(slot.format==='Диоген'?'Диоген':'Мастер-класс');document.getElementById('booking-activity').textContent=title;const start=slotMinutes(slot);const defaultEnd=Math.min(start+60,slotEndMinutes(slot));bookingState.end=slot.format==='Диоген'?defaultEnd:slotEndMinutes(slot);renderBookingModal();document.getElementById('booking-modal').classList.remove('hidden');}
function bookingMaxTickets(){if(!bookingState)return 0;const {slot,start,end}=bookingState;if(slot.format!=='Диоген')return Number(slot.free)||0;const day=slot.start.split(' ')[0];let max=Infinity;for(let t=start;t<end;t+=60){const part=bookingSlots.find(s=>s.format==='Диоген'&&s.start.startsWith(day)&&slotMinutes(s)===t);if(!part)return 0;max=Math.min(max,Number(part.free)||0);}return Number.isFinite(max)?max:0;}
function renderBookingModal(){if(!bookingState)return;const {slot,start,end}=bookingState;document.getElementById('booking-start').textContent=`${pad(Math.floor(start/60))}:${pad(start%60)}`;document.getElementById('booking-end').textContent=`${pad(Math.floor(end/60))}:${pad(end%60)}`;document.getElementById('booking-date').textContent=formatBookingDate(slot.start);const controls=document.getElementById('booking-duration-controls');controls.classList.toggle('hidden',slot.format!=='Диоген');const up=document.getElementById('booking-end-up'),down=document.getElementById('booking-end-down');if(slot.format==='Диоген'){const ends=availableDiogenEnd(slot,Number(document.getElementById('booking-tickets-input')?.value)||1);up.disabled=!ends.includes(end+60);down.disabled=end<=start+60;up.setAttribute('aria-disabled',String(up.disabled));down.setAttribute('aria-disabled',String(down.disabled));}const max=bookingMaxTickets();const input=document.getElementById('booking-tickets-input');input.max=String(Math.max(1,max));input.value=String(Math.min(Number(input.value)||1,Math.max(1,max)));}
function formatBookingDate(s){const d=dateKey(s);return d.toLocaleDateString('ru-RU',{day:'numeric',month:'long'});}
function changeDiogenEnd(direction){if(!bookingState||bookingState.slot.format!=='Диоген')return;const ends=availableDiogenEnd(bookingState.slot,Number(document.getElementById('booking-tickets-input')?.value)||1);const target=bookingState.end+direction*60;if(target<bookingState.start+60||!ends.includes(target))return;bookingState.end=target;renderBookingModal();}
function closeBooking(){const modal=document.getElementById('booking-modal');if(modal)modal.classList.add('hidden');bookingState=null;}
function selectSlot(slot){if(!slot.available||Number(slot.free||0)<=0){showMessage('В этом слоте больше нет свободных мест.');return;}if(!selectedCalendar.format){showMessage('Сначала выберите активность.');return;}if(selectedCalendar.format==='МК'){if(slot.format!=='МК'||norm(slot.name)!==norm(selectedCalendar.name)){showMessage('Выберите слот выбранного мастер-класса.');return;}if(!candidateSlotsForEvent(selectedCalendar.name).some(x=>x.slotId===slot.slotId)){showMessage('Этот слот не подходит по длительности мастер-класса.');return;}}else if(selectedCalendar.format==='Диоген'&&slot.format!=='Диоген'){showMessage('Выберите свободный час Диогена.');return;}openBooking(slot);}
async function submitBooking(){if(!bookingState)return;const {slot,start,end}=bookingState;const input=document.getElementById('booking-tickets-input'),tickets=Number(input.value)||0,max=bookingMaxTickets();if(!Number.isInteger(tickets)||tickets<1||tickets>max){showMessage(`Введите целое число от 1 до ${max}.`);return;}const endTime=`${pad(Math.floor(end/60))}:${pad(end%60)}`;closeBooking();showMessage('Создаём бронь...');try{const result=await apiBook({...slot,start:`${slot.start.split(' ')[0]} ${pad(Math.floor(start/60))}:${pad(start%60)}`},tickets,endTime);showMessage(`Бронь №${result.booking.id} создана: ${result.booking.date} ${result.booking.time}, ${result.booking.tickets} мест.`);await loadBookingData();}catch(e){showMessage(`Не удалось записаться: ${e.message}`);}}
function goToCalendar(type,name=''){if(type==='masterclass'){selectedCalendar={format:'МК',name};}else if(type==='diogen'){selectedCalendar={format:'Диоген',name};}else{selectedCalendar={format:'',name:''};}renderCalendar();if(selectedCalendar.format)showMessage(`Расписание: ${name||selectedCalendar.format}.`);setTimeout(()=>document.querySelector('.calendar-card')?.scrollIntoView({behavior:'smooth',block:'start'}),40);}
function showMessage(t){message.textContent=t;message.classList.remove('hidden');message.scrollIntoView({behavior:'smooth',block:'nearest'});}function closeActivity(){activityModal.classList.add('hidden');}
modalClose.addEventListener('click',closeActivity);modalOk.addEventListener('click',closeActivity);activityModal.addEventListener('click',e=>{if(e.target===activityModal)closeActivity();});eventsClose.addEventListener('click',closeEvents);eventsModal.addEventListener('click',e=>{if(e.target===eventsModal)closeEvents();});
renderCalendar();window.addEventListener('resize',renderCalendar);Promise.all([loadActivities(),loadEvents(),loadBookingData()]).catch(()=>{});