const SHEET_ID='1FcetqNVvXNI78h0mcQdEJBEVXzkHcgaddFrCn2VOugk';
const SHEET_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=${encodeURIComponent('Активности')}&headers=0&range=A2:D`;
const EVENTS_SHEET_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=${encodeURIComponent('Ивенты')}&headers=0&range=A2:I`;
const BOOKING_API_URL='https://script.google.com/macros/s/AKfycbwpYRqIunVa1uBfMqaf9HY4ICKXeeaCUbYLtoBxYT6e0_tYyBSvgiVfmeU-3SkEC2SqxQ/exec';
const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();tg.setBackgroundColor?.('bg_color');}
const user=tg?.initDataUnsafe?.user,hello=document.getElementById('hello');if(user)hello.textContent=`Здравствуйте, ${user.first_name||'гость'}!`;
const activitiesContainer=document.getElementById('activities'),calendar=document.getElementById('calendar'),message=document.getElementById('message'),activityModal=document.getElementById('activity-modal'),activityTitle=document.getElementById('activity-title'),activityDescription=document.getElementById('activity-description'),activityImageWrap=document.getElementById('activity-image-wrap'),activityImage=document.getElementById('activity-image'),modalClose=document.getElementById('modal-close'),modalOk=document.getElementById('modal-ok'),eventsModal=document.getElementById('events-modal'),eventsTitle=document.getElementById('events-title'),eventsList=document.getElementById('events-list'),eventsClose=document.getElementById('events-close');
const fallbackActivities=[{key:'diogen',title:'Диоген',description:'Можно прийти в мастерскую и провести время в своём ритме: поработать над чем-то своим, потискать кожу, попить чаю, посидеть в тишине или вообще ничего не делать.',image:''},{key:'masterclass',title:'Мастер-класс',description:'Вы выбираете изделие и приходите делать его вместе с мастером. Мастер-класс проходит в заданное время и длится столько, сколько указано в его описании.',image:''},{key:'order',title:'Обсудить заказ',description:'Если вы хотите сделать изделие на заказ, можно прийти в мастерскую лично: обсудить задумку, материалы, размеры, детали и все нюансы будущей вещи.',image:''}];let activities=fallbackActivities,events=[],bookingSlots=[];
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');
function parse(t){const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<=a)throw Error('Google Таблица не вернула данные.');return JSON.parse(t.slice(a,b+1));}function cell(c,i,f=''){return c[i]?.v??f;}function norm(v){return String(v||'').trim().toLowerCase();}
async function loadActivities(){activitiesContainer.innerHTML='<div class="loading">Загрузка активностей...</div>';try{const r=await fetch(SHEET_URL,{cache:'no-store'});const j=parse(await r.text());activities=j.table.rows.map((x,i)=>{const c=x.c||[];return{key:String(cell(c,0,`activity-${i}`)).trim().toLowerCase(),title:String(cell(c,1,'Без названия')).trim(),description:String(cell(c,2,'')).trim(),image:String(cell(c,3,'')).trim()};}).filter(x=>x.key&&x.title);renderActivities();}catch(e){activitiesContainer.innerHTML=`<div class="load-error">Не удалось загрузить активности: ${esc(e.message)}</div>`;}}
async function loadEvents(){try{const r=await fetch(EVENTS_SHEET_URL,{cache:'no-store'});const j=parse(await r.text());const rows=j.table.rows||[];events=rows.map((x,i)=>{const c=x.c||[];return{activity:String(cell(c,0,'')).trim(),name:String(cell(c,1,'Без названия')).trim(),price:String(cell(c,2,'')).trim(),age:String(cell(c,3,'')).trim(),duration:String(cell(c,4,'')).trim(),complexity:String(cell(c,5,'')).trim(),image:String(cell(c,6,'')).trim(),description:String(cell(c,8,'')).trim(),index:i};}).filter(x=>x.activity&&x.name);}catch(e){console.error(e);events=[];}}
async function loadBookingData(){try{const r=await fetch(BOOKING_API_URL,{cache:'no-store'});const j=await r.json();if(!j.ok)throw Error(j.error||'Не удалось получить календарь.');bookingSlots=Array.isArray(j.slots)?j.slots:[];renderCalendar();return j;}catch(e){bookingSlots=[];calendar.innerHTML=`<div class="load-error">Не удалось загрузить календарь: ${esc(e.message)}</div>`;throw e;}}
async function apiBook(slot,tickets){if(!user?.id)throw Error('Не удалось определить Telegram ID. Откройте запись внутри Telegram.');const format=slot.format||'';const payload={action:'book',telegramId:String(user.id),name:String(user.first_name||user.username||'гость'),format,eventName:slot.name,date:slot.start.split(' ')[0],time:slot.start.split(' ')[1],tickets:Number(tickets)};const r=await fetch(BOOKING_API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const j=await r.json();if(!j.ok)throw Error(j.error||'Не удалось создать бронь.');return j;}
function renderActivities(){activitiesContainer.innerHTML=activities.map(a=>`<button class="choice" type="button" data-action="${esc(a.key)}"><span class="choice-icon">${a.key==='diogen'?'◌':a.key==='masterclass'?'✦':'✎'}</span><span><strong>${esc(a.title)}</strong><small>${esc(a.description)}</small></span><span class="choice-calendar"><span class="choice-calendar-icon">▣</span><span class="choice-calendar-arrow">↓</span></span></button>`).join('');activitiesContainer.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',e=>e.target.closest('.choice-calendar')?openEventChooser(b.dataset.action):openActivity(b.dataset.action)));}
function openActivity(k){const a=activities.find(x=>x.key===k);if(!a)return;activityTitle.textContent=a.title;activityDescription.textContent=a.description;if(a.image){activityImage.src=a.image;activityImage.alt=a.title;activityImageWrap.classList.remove('hidden');}else activityImageWrap.classList.add('hidden');activityModal.classList.remove('hidden');}
function stars(v){const n=Math.max(0,Math.min(5,parseInt(v,10)||0));return[1,2,3,4,5].map(i=>`<span class="complexity-star${i>5-n?' filled':''}">★</span>`).join('');}
function openEventChooser(k){const key=norm(k);if(key==='order'){closeEvents();goToCalendar('order');return;}const a=activities.find(x=>norm(x.key)===key);if(!a)return;const list=events.filter(x=>norm(x.activity)===key);eventsTitle.textContent=a.title;eventsList.innerHTML=list.length?list.map((e,i)=>`<article class="event-card"><div class="event-image-wrap ${e.image?'':'empty'}">${e.image?`<img class="event-image" src="${esc(e.image)}" alt="${esc(e.name)}">`:'Фото пока нет'}<div class="event-overlay"><div class="event-text-block"><h3>${esc(e.name)}</h3><strong class="event-price">${esc(e.price||'—')} р</strong></div><div class="event-age"><strong>${esc(e.age||'—')}</strong></div><div class="event-duration"><strong>${esc(e.duration||'—')}</strong></div><div class="event-complexity"><strong class="complexity-stars">${stars(e.complexity)}</strong></div></div><div class="event-actions"><button class="event-details" type="button" data-i="${i}">Подробнее</button><button class="event-book" type="button" data-i="${i}">Записаться</button></div></div><div class="event-description hidden" data-i="${i}">${esc(e.description||'Описание пока придумываем)')}</div></article>`).join(''):'<div class="events-empty">Пока нет доступных вариантов.</div>';eventsList.querySelectorAll('.event-details').forEach(b=>b.addEventListener('click',()=>{const d=eventsList.querySelector(`.event-description[data-i="${b.dataset.i}"]`);if(!d)return;const open=!d.classList.contains('hidden');d.classList.toggle('hidden');b.textContent=open?'Подробнее':'Свернуть';}));eventsList.querySelectorAll('.event-book').forEach(b=>b.addEventListener('click',()=>{const e=list[+b.dataset.i];closeEvents();goToCalendar(norm(e.activity),e.name);}));eventsModal.classList.remove('hidden');}
function closeEvents(){eventsModal.classList.add('hidden');}
function slotLabel(s){if(s.occupied>0)return`${s.format==='МК'?'МК':'Диоген'} · ${s.occupied}/${s.capacity}`;return'свободно';}
function slotClass(s){if(!s.available)return'closed';if(s.occupied>0)return s.format==='МК'?'mk':'dio';return'free';}
function groupSlotsByDay(){const groups={};bookingSlots.forEach(s=>{const date=s.start.split(' ')[0];(groups[date]||(groups[date]=[])).push(s);});return Object.keys(groups).sort().map(date=>({date,slots:groups[date].sort((a,b)=>a.start.localeCompare(b.start))}));}
function renderCalendar(){const groups=groupSlotsByDay();calendar.innerHTML=groups.length?groups.map(d=>{const [day,month,year]=d.date.split('.').map(Number);const x=new Date(year,month-1,day,12,0,0);return`<article class="day"><div class="day-title"><span>${x.toLocaleDateString('ru-RU',{day:'numeric',month:'long',weekday:'long'})}</span></div><div class="slots">${d.slots.map(s=>{const state=slotClass(s);return`<button class="slot ${state}" type="button" data-slot-id="${esc(s.slotId)}"><strong>${esc(s.start.split(' ')[1])}–${esc(s.end.split(' ')[1])}</strong><small>${esc(slotLabel(s))}</small></button>`;}).join('')}</div></article>`;}).join(''):'<div class="events-empty">Пока нет доступных слотов.</div>';calendar.querySelectorAll('.slot').forEach(b=>b.addEventListener('click',()=>{const s=bookingSlots.find(x=>x.slotId===b.dataset.slotId);if(s)selectSlot(s);}));}
function selectSlot(slot){if(!slot.available){showMessage('В этом слоте больше нет свободных мест.');return;}const max=Number(slot.free)||0;const min=Number(slot.minTickets)||1;let tickets=min;if(max<min){showMessage(`Свободно только ${max} мест.`);return;}const answer=window.prompt(`«${slot.name}»\n${slot.start}–${slot.end}\nСвободно: ${max}\nКоличество мест (от ${min} до ${max}):`,String(tickets));if(answer===null)return;tickets=Number(answer);if(!Number.isInteger(tickets)||tickets<min||tickets>max){showMessage(`Введите целое число от ${min} до ${max}.`);return;}bookSlot(slot,tickets);}
async function bookSlot(slot,tickets){showMessage('Создаём бронь...');try{const result=await apiBook(slot,tickets);showMessage(`Бронь №${result.booking.id} создана: ${result.booking.date} ${result.booking.time}, ${result.booking.tickets} мест.`);await loadBookingData();}catch(e){showMessage(`Не удалось записаться: ${e.message}`);}}
function goToCalendar(type,name=''){document.querySelectorAll('.slot.highlighted').forEach(x=>x.classList.remove('highlighted'));const matching=bookingSlots.filter(s=>s.available&&((type==='masterclass'&&s.format==='МК'&&(!name||s.name===name))||(type==='diogen'&&s.format==='Диоген')||(type==='order')));matching.forEach(s=>document.querySelector(`.slot[data-slot-id="${CSS.escape(s.slotId)}"]`)?.classList.add('highlighted'));showMessage(type==='masterclass'&&name?`Подсвечены места для «${name}».`:type==='order'?'Подсвечены свободные часы для обсуждения заказа.':'Подсвечены все свободные часы.');setTimeout(()=>document.querySelector('.calendar-card')?.scrollIntoView({behavior:'smooth',block:'start'}),40);}
function showMessage(t){message.textContent=t;message.classList.remove('hidden');message.scrollIntoView({behavior:'smooth',block:'nearest');}function closeActivity(){activityModal.classList.add('hidden');}
modalClose.addEventListener('click',closeActivity);modalOk.addEventListener('click',closeActivity);activityModal.addEventListener('click',e=>{if(e.target===activityModal)closeActivity();});eventsClose.addEventListener('click',closeEvents);eventsModal.addEventListener('click',e=>{if(e.target===eventsModal)closeEvents();});
renderCalendar();Promise.all([loadActivities(),loadEvents(),loadBookingData()]).catch(()=>{});